[[inputs.exec]]
  commands = ["/usr/local/bin/fetch_byd.py"]
  alias = "byd-input"
  name_override = "byd"
  data_format = "json"
  interval = "1m"
  json_query = ""
  json_time_key = "timestamp"
  json_time_format = "unix"
  tag_keys = ["module","firmware_A","firmware_B","table_A","table_B"]
