[[inputs.exec]]
  commands = ["/usr/local/bin/fetch_tibber.py"]
  alias = "tibber-input"
  name_override = "tibber"
  interval = "1h"
  collection_offset = "10m"
  collection_jitter = "2m"
  data_format = "json"
  json_query = ""
  json_time_key = "time"
  json_time_format = "2006-01-02T15:04:05.000-07:00"
